[package]
name = "rust-ddd"
version = "0.1.0"
authors = ["Flavius Aspra <flavius.as@gmail.com>"]
edition = "2018"

[dependencies]
uuid = { version = "0.7", features = ["v4"] }
proc_macro = { path = "proc_macro" }

[[bin]]
name = "rust-ddd"
path = "src/main.rs"
test = false
